-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
  -- {
  --   'mfussenegger/nvim-dap',
  --   config = function()
  --     local dap, dapui = require("dap"), require("dapui")
  --     dap.listeners.before.attach.dapui_config = function()
  --       dapui.open()
  --     end
  --     dap.listeners.before.launch.dapui_config = function()
  --       dapui.open()
  --     end
  --     dap.listeners.before.event_terminated.dapui_config = function()
  --       dapui.close()
  --     end
  --     dap.listeners.before.event_exited.dapui_config = function()
  --       dapui.close()
  --     end
  --   end,
  -- },
  --
  -- {
  --   'rcarriga/nvim-dap-ui', 
  --   dependencies = {"mfussenegger/nvim-dap", "nvim-neotest/nvim-nio"},
  --   config = function()
  --     require("dapui").setup()
  --   end,
  -- },
}
