# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./
{
  config,
  lib,
  pkgs,
  ...
}: let
  # scriptsDir = ../../bin;
in {
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "kerby";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  home.activation.cleanupStaleBackups = config.lib.dag.entryBefore ["checkLinkTargets"] ''
    find "$HOME"/.config -name "*.BAK" -delete 2>/dev/null || true
  '';

  home.activation.restartWaybar = config.lib.dag.entryAfter ["writeBoundary"] ''
    ${pkgs.procps}/bin/pkill -u $USER '\.waybar-wrapp' 2>/dev/null || true
  '';

  home.activation.reloadSystemdUser = config.lib.dag.entryAfter ["writeBoundary"] ''
    XDG_RUNTIME_DIR=/run/user/1000 ${pkgs.systemd}/bin/systemctl --user daemon-reload 2>/dev/null || echo "User systemd not running (normal during boot)"
  '';
  # Export compiled nixvim config to a syncthing-shared folder for Termux.
  # The nixvim init.lua lives at a Nix store path that changes every rebuild;
  # this script extracts it from the nvim wrapper and copies it to ~/Sync/nvim/.
  # Also generates a lazy.nvim plugin spec + Termux bootstrap init.lua.
  home.activation.exportNvimConfig = config.lib.dag.entryAfter ["writeBoundary"] ''
    SYNC_DIR="$HOME/Sync/nvim"
    mkdir -p "$SYNC_DIR"

    # Extract compiled init.lua path from the nvim wrapper's VIMINIT export
    NVIM_BIN=$(readlink -f "/run/current-system/sw/bin/nvim" 2>/dev/null || readlink -f "$(command -v nvim)" 2>/dev/null || echo "")
    if [ -n "$NVIM_BIN" ] && [ -f "$NVIM_BIN" ]; then
      INIT_LUA=$(grep -oP "/nix/store/[^'\\\\]+-init\.lua" "$NVIM_BIN" 2>/dev/null || echo "")
      if [ -n "$INIT_LUA" ] && [ -f "$INIT_LUA" ]; then
        cp "$INIT_LUA" "$SYNC_DIR/init.lua"
      fi
    fi

    # lazy.nvim plugin spec — maps nixvim plugins to GitHub repos for Termux
    cat > "$SYNC_DIR/lazy-spec.lua" << 'LAZY_EOF'
    return {
      { "ellisonleao/gruvbox.nvim", lazy = false },
      { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" }, lazy = false },
      { "nvim-telescope/telescope-fzf-native.nvim", build = "make", lazy = false },
      { "nvim-telescope/telescope-ui-select.nvim", lazy = false },
      { "hrsh7th/nvim-cmp", lazy = false },
      { "hrsh7th/cmp-nvim-lsp", lazy = false },
      { "hrsh7th/cmp-path", lazy = false },
      { "saadparwaiz1/cmp_luasnip", lazy = false },
      { "L3MON4D3/LuaSnip", lazy = false },
      { "neovim/nvim-lspconfig", lazy = false },
      { "folke/neodev.nvim", lazy = false },
      { "nvimdev/lspsaga.nvim", lazy = false },
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate", lazy = false },
      { "folke/which-key.nvim", lazy = false },
      { "folke/trouble.nvim", lazy = false },
      { "folke/todo-comments.nvim", lazy = false },
      { "folke/fidget.nvim", lazy = false },
      { "nvim-tree/nvim-web-devicons", lazy = false },
      { "nvim-neo-tree/neo-tree.nvim", dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim", "nvim-tree/nvim-web-devicons" }, lazy = false },
      { "echasnovski/mini.nvim", lazy = false },
      { "lewis6991/gitsigns.nvim", lazy = false },
      { "kdheepak/lazygit.nvim", lazy = false },
      { "mfussenegger/nvim-dap", lazy = false },
      { "rcarriga/nvim-dap-ui", dependencies = { "nvim-neotest/nvim-nio" }, lazy = false },
      { "leoluz/nvim-dap-go", lazy = false },
      { "stevearc/conform.nvim", lazy = false },
      { "numToStr/Comment.nvim", lazy = false },
      { "windwp/nvim-autopairs", lazy = false },
      { "tpope/vim-sleuth", lazy = false },
    }
    LAZY_EOF

    # Termux bootstrap — loads plugins via lazy.nvim, then sources the nixvim init.lua
    cat > "$SYNC_DIR/termux-init.lua" << 'TERMUX_EOF'
    -- Termux neovim bootstrap
    -- Loads plugins via lazy.nvim, then sources the nixvim-compiled init.lua
    -- synced from NixOS via syncthing.
    --
    -- Usage: nvim -u ~/Sync/nvim/termux-init.lua
    -- Or:   symlink ~/.config/nvim/init.lua -> ~/Sync/nvim/termux-init.lua

    -- Path to the syncthing-synced nvim folder (adjust for your Android setup)
    local sync_dir = vim.fn.expand("~/Sync/nvim")

    -- Bootstrap lazy.nvim
    local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
    if not vim.loop.fs_stat(lazypath) then
      vim.fn.system({
        "git", "clone", "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", lazypath,
      })
    end
    vim.opt.rtp:prepend(lazypath)

    -- Load plugin spec
    local ok, spec = pcall(dofile, sync_dir .. "/lazy-spec.lua")
    if not ok then
      vim.notify("Could not load lazy-spec.lua from " .. sync_dir, vim.log.levels.ERROR)
      return
    end

    require("lazy").setup(spec, {
      install = { missing = true },
      -- Point lazy's data dir to Termux-friendly location
      root = vim.fn.stdpath("data") .. "/lazy",
    })

    -- After plugins are loaded, source the nixvim-compiled init.lua
    vim.api.nvim_create_autocmd("User", {
      pattern = "LazyDone",
      once = true,
      callback = function()
        local ok, err = pcall(dofile, sync_dir .. "/init.lua")
        if not ok then
          vim.notify("nixvim init.lua error: " .. tostring(err), vim.log.levels.WARN)
        end
      end,
    })
    TERMUX_EOF
  '';

  stylix.targets.qt.enable = false;

  dconf.settings = {
    "org/gnome/desktop/peripherals/mouse" = {natural-scroll = true;};
    # "org/gnome/desktop/input-sources" = {xkb-options = ["ctrl:nocaps"];};
  };

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    dina-font
    font-awesome
    fira-code
    fira-code-symbols
    liberation_ttf
    inter
    mplus-outline-fonts.githubRelease
    nerd-fonts.fira-code
    nerd-fonts.inconsolata
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    montserrat
    noto-fonts-color-emoji
    roboto-mono
    gruvbox-gtk-theme
    # gruvbox-plus-icons
    poppins
    source-sans
    papirus-icon-theme
  ];

  home.file.".icons/default".source = "${pkgs.vanilla-dmz}/share/icons/Vanilla-DMZ";

  # LSP config for the Oh My Pi coding agent
  home.file."nixcfg/.omp/lsp.json".text = builtins.toJSON {
    servers = {
      nixd = {
        settings = {
          nixd = {
            formatting.command = ["alejandra" "--quiet"];
          };
        };
      };
    };
  };
  # Override Wine-managed Eagle desktop entry
  # Uses direct .exe path (not .lnk) to avoid blank explorer.exe windows,
  # and sets PULSE_SERVER so winepulse.drv connects to PipeWire-Pulse.
  home.file.".local/share/applications/wine/Programs/Eagle/Eagle.desktop".text = ''
    [Desktop Entry]
    Name=Eagle
    Comment=
    Exec=env WINEPREFIX=$HOME/.wine-eagle WINEARCH=win64 PULSE_SERVER=unix:/run/user/1000/pulse/native wine "C:\\users\\kerby\\AppData\\Roaming\\Eagle\\Eagle.exe"
    Type=Application
    StartupNotify=true
    Path=${config.home.homeDirectory}/.wine-eagle/drive_c/users/kerby/AppData/Roaming/Eagle
    Icon=141A_Eagle.0
    StartupWMClass=eagle.exe
  '';

  home.sessionVariables = {
    EDITOR = "nvim";
    NIXOS_OZONE_WL = "1";
    WINEPREFIX = "$HOME/.wine-eagle";
    WINEARCH = "win64";
  };

  home.sessionPath = [
    "$HOME/bin:$HOME/.cargo/bin"
    "$HOME/.local/bin"
  ];

  gtk = {
    gtk4.theme = lib.mkForce null;
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus";
    };
    gtk3.extraConfig.Settings = ''gtk-application-prefer-dark-themes=1'';
    gtk4.extraConfig.Settings = ''gtk-application-prefer-dark-themes=1'';
  };

  systemd.user.services.dropbox = {
    Unit = {
      Description = "Dropbox service";
    };
    Install = {
      WantedBy = ["default.target"];
    };
    Service = {
      ExecStart = "${pkgs.dropbox}/bin/dropbox";
      Restart = "on-failure";
    };
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.11"; # Please read the comment before changing.

  systemd.user.startServices = false;
}
