# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./
{
  config,
  lib,
  pkgs,
  ...
}: let
  scriptsDir = ../../bin;
in {
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "kerby";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";
  home.file = {
    "bin/resolve-watch" = {
      source = "${scriptsDir}/resolve-watch.sh";
      executable = true;
    };
    "bin/transcode-for-resolve" = {
      source = "${scriptsDir}/transcode-for-resolve.sh";
      executable = true;
    };
    "bin/transcode-for-web" = {
      source = "${scriptsDir}/transcode-for-web.sh";
      executable = true;
    };
  };

  dconf.settings = {
    "org/gnome/desktop/peripherals/mouse" = {natural-scroll = true;};
    # "org/gnome/desktop/input-sources" = {xkb-options = ["ctrl:nocaps"];};
  };

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    dina-font
    font-awesome
    fira-code
    fira-code-symbols
    liberation_ttf
    mplus-outline-fonts.githubRelease
    nerd-fonts.fira-code
    nerd-fonts.inconsolata
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    roboto-mono
    gruvbox-gtk-theme
    # gruvbox-plus-icons
    papirus-icon-theme
  ];

  home.file.".icons/default".source = "${pkgs.vanilla-dmz}/share/icons/Vanilla-DMZ";

  home.sessionVariables = {
    EDITOR = "nvim";
    NIXOS_OZONE_WL = "1";
  };

  home.sessionPath = [
    "$HOME/bin:$HOME/.cargo/bin"
  ];

  gtk = {
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus";
    };
    gtk3.extraConfig.Settings = ''gtk-application-prefer-dark-themes=1'';
    gtk4.extraConfig.Settings = ''gtk-application-prefer-dark-themes=1'';
  };

  systemd.user.services.dropbox = {
    Unit = {
      Description = "Dropbox service";
    };
    Install = {
      WantedBy = ["default.target"];
    };
    Service = {
      ExecStart = "${pkgs.dropbox}/bin/dropbox";
      Restart = "on-failure";
    };
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.11"; # Please read the comment before changing.
}
